version: '3.2'

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
       - '9000:9000'
       - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:

networks: 
  net:
    driver: bridge
    