version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
        - '6379:6379'
    volumes:    
        - 'redis_data:/data'
    
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    ports:
        - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
        - redis
volumes:
  redis_data: